name: CI/CD Workflow Without Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t simple-ci-cd-project:latest .

      - name: Verify Docker image locally
        run: |
          docker run --name simple-container -d -p 8080:3000 simple-ci-cd-project:latest
          docker ps -a  # Kapsayıcı durumunu listele
          docker logs simple-container  # Kapsayıcı loglarını kontrol et
          sleep 10
          curl -f http://localhost:8080
          docker stop simple-container

